url = "mysql://root:password@localhost/newsman"
dir = "~/.config/newsman/newsletters/"
smtp_username = "newsletter@example.com"
smtp_password = "example"
sender = "newsletter@example.com"
relay = "mail.example.com"
interval = 0
api_endpoint = "http://127.0.0.1:3600/"
